### ISSUE TITLE
Looks like snek is failing?

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#111]
```
db 2022-10-28T11:57:28.757Z ERROR null value in column "name" of relation "series" violates not-null constraint INSERT INTO "series"("id", "issuer", "unique", "unique_collectors", "sold", "total", "average_price", "floor_price", "highest_sale", "buys", "volume", "name", "metadata", "image", "emote_count") VALUES ($1, $2, $3, $4, $5, $6, $7, DEFAULT, $8, $9, $10, $11, $12, $13, $14), ($15, $16, $17, $18, $19, $20, $21, DEFAULT, $22, $23, $24, $25, $26, $27, $28) {"state_code":"23502","detail":"Failing row contains (3813476019, 1, 1, 1, 3, 0.00000000000000000000, null, 3, 1221667000000, null, null, null, bXhe4tuWvxtpzz3Wo1MMwZLr1awBJTJddLfXYsGXXjsb5pWfw, 500000000000, 0)."}
db 2022-10-28T11:57:28.759Z ERROR current transaction is aborted, commands ignored until end of transaction block INSERT INTO "spotlight"("id", "collections", "unique_collectors", "unique", "sold", "total", "average", "volume") VALUES ($1, $2, $3, $4, $5, $6, $7, $8), ($9, $10, $11, $12, $13, $14, $15, $16) {"state_code":"25P02"}
db 2022-10-28T11:57:28.768Z ERROR current transaction is aborted, commands ignored until end of transaction block SELECT "Offer"."id" AS "Offer_id", "Offer"."block_number" AS "Offer_block_number", "Offer"."caller" AS "Offer_caller", "Offer"."created_at" AS "Offer_created_at", "Offer"."expiration" AS "Offer_expiration", "Offer"."price" AS "Offer_price", "Offer"."status" AS "Offer_status", "Offer"."updated_at" AS "Offer_updated_at", "Offer"."nft_id" AS "Offer_nft_id" FROM "offer" "Offer" WHERE ("Offer"."id" = $1) LIMIT 1 {"state_code":"25P02"}
processor 2022-10-28T11:57:28.770Z CRITICAL sqd:processor QueryFailedError: current transaction is aborted, commands ignored until end of transaction block
    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SelectQueryBuilder.loadRawResults (/squid/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2056:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/squid/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1916:26)
    at async SelectQueryBuilder.getRawAndEntities (/squid/node_modules/typeorm/query-builder/SelectQueryBuilder.js:645:29)
    at async SelectQueryBuilder.getOne (/squid/node_modules/typeorm/query-builder/SelectQueryBuilder.js:672:25)
    at async handleOfferAccept (/squid/lib/mappings/index.js:278:40)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:506:25)
    at async /squid/node_modules/@subsquid/typeorm-store/lib/database.js:157:13
    at async EntityManager.transaction (/squid/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
```

@roiLeo can u please check ? 
I am low on 🔋 
<img width="370" alt="Screenshot 2022-10-28 at 13 58 26" src="https://user-images.githubusercontent.com/22471030/198582051-e26f2c3f-859d-4682-8628-bd142156d2c1.png">

**Comment by roiLeo** [comment]
Running well on main branch Rococo

<img width="709" alt="Capture d’écran 2022-10-28 à 2 04 15 PM" src="https://user-images.githubusercontent.com/9987732/198582843-4d1ddcf0-08f8-4eef-be10-70ea324f1462.png">

**Comment by vikiival** [comment]
Thank you 🤗
