### ISSUE TITLE
🐛 : Glitch in the matrix

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#126]
Basically somehow the same NFT wants to be created twice
```
☐  pending   [NFT++]: 1098515
⬤  debug     nft: {
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
  "blockNumber": "1098515",
  "timestamp": "2022-11-04T10:17:06.189Z",
  "collectionId": "1631038496",
  "sn": "2",
  "metadata": "ipfs://ipfs/bafkreiez4gh2u453pv2sjolykwtodj2ivdxad6hxw4w4ui5zzs26s5hyga"
}
final NFTEntity { id: '1631038496-2' }
⬤  debug     metadata: ipfs://ipfs/bafkreiez4gh2u453pv2sjolykwtodj2ivdxad6hxw4w4ui5zzs26s5hyga
✔  success   [MINT] 1631038496-2
☐  pending   [NFT++]: 1098515
⬤  debug     nft: {
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
  "blockNumber": "1098515",
  "timestamp": "2022-11-04T10:17:06.189Z",
  "collectionId": "1631038496",
  "sn": "2",
  "metadata": "ipfs://ipfs/bafkreiez4gh2u453pv2sjolykwtodj2ivdxad6hxw4w4ui5zzs26s5hyga"
}
final NFTEntity {
  id: '1631038496-2',
  blockNumber: 1098515n,
  burned: false,
  createdAt: 2022-11-04T10:17:06.189Z,
  currentOwner: 'bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW',
  hash: '18d66010102c4a87e316139ae4f5fe18',
  issuer: 'bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW',
  metadata: 'ipfs://ipfs/bafkreiez4gh2u453pv2sjolykwtodj2ivdxad6hxw4w4ui5zzs26s5hyga',
  name: 'SUCCESS',
  price: 0n,
  royalty: undefined,
  recipient: null,
  sn: '2',
  updatedAt: 2022-11-04T10:17:06.189Z
}
22:48:07 FATAL sqd:processor ReferenceError: [PROBLEM] Entity NFT needs to be remintable
                                 at needTo (/Users/vikival/Documents/Work/KodaDot/indexer/snek/lib/mappings/utils/consolidator.js:45:15)
                                 at plsBe (/Users/vikival/Documents/Work/KodaDot/indexer/snek/lib/mappings/utils/consolidator.js:35:12)
                                 at handleTokenCreate (/Users/vikival/Documents/Work/KodaDot/indexer/snek/lib/mappings/index.js:112:30)
                                 at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                 
```

**Comment by vikiival** [comment]
Handler was initialized twice.

a0d852ba5c6cf34a6acc00a97c447b6b32309783
