### ISSUE TITLE
main branch fail indexing

### ISSUE THREAD

**Issue by roiLeo** [kodadot/snek#165]
BLOCK 1795339

```log
✔  success   [ROYALTY] 331660682-8 by bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW
☐  pending   [COLECTTION++]: 1795339
15:06:47 FATAL sqd:processor AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

                               (0, assert_1.default)(this.isV81)

                                 at get asV81 [as asV81] (/Users/edics-osx2/Desktop/wip/snek/lib/types/events.js:575:30)
                                 at getCreateCollectionEvent (/Users/edics-osx2/Desktop/wip/snek/lib/mappings/utils/getters.js:10:84)
                                 at unwrap (/Users/edics-osx2/Desktop/wip/snek/lib/mappings/utils/extract.js:19:23)
                                 at handleCollectionCreate (/Users/edics-osx2/Desktop/wip/snek/lib/mappings/index.js:65:40)
                                 at HandlerRunner.processBlock (/Users/edics-osx2/Desktop/wip/snek/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:505:31)
                                 at /Users/edics-osx2/Desktop/wip/snek/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:471:29
                                 at /Users/edics-osx2/Desktop/wip/snek/node_modules/@subsquid/typeorm-store/lib/database.js:157:19
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async EntityManager.transaction (/Users/edics-osx2/Desktop/wip/snek/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
                                 at async FullTypeormDatabase.runTransaction (/Users/edics-osx2/Desktop/wip/snek/node_modules/@subsquid/typeorm-store/lib/database.js:155:9)
                                 generatedMessage: true
                                 code: ERR_ASSERTION
                                 actual: false
                                 expected: true
                                 operator: ==
                                 blockHeight: 1795339
                                 blockHash: 0x5882baa70e49ae0101d87e320ec6ee3f71f4df880f2e4592e025ec7aa9ff7470
make: *** [process] Error 1
```

**Comment by roiLeo** [comment]
Fix is to introduce `v92` events
