### ISSUE TITLE
handleRoyaltyPay -  Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by petersopko** [kodadot/snek#31]
while trying to process, I ran into this error: 
```
*  note      Welcome to the Processor! https://basilisk-test.indexer.gc.subsquid.io/v4/graphql
Prometheus metrics are served at port 60739
[ ]  pending   [PAY ROYALTY]: 28058
.isLatest, .asLatest properties are deprecated, if you believe this is a mistake, please leave
a comment at https://github.com/subsquid/squid/issues/9
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at handleRoyaltyPay (D:\KodaDot\snek\lib\mappings\index.js:207:41)
    at D:\KodaDot\snek\node_modules\@subsquid\substrate-processor\lib\processor.js:285:35
    at D:\KodaDot\snek\node_modules\@subsquid\substrate-processor\lib\db.js:69:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by petersopko** [comment]
my bad, already done.
