### ISSUE TITLE
Series insight fail

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#87]
```json
{
  "errors": [
    {
      "message": "Cannot query field \"highestSale\" on type \"Series\".",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "GraphQLError: Cannot query field \"highestSale\" on type \"Series\".",
            "    at Object.Field (/squid/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
            "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
            "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
            "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
            "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
            "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
            "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
          ]
        }
      }
    },
    {
      "message": "Cannot query field \"emoteCount\" on type \"Series\".",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "GraphQLError: Cannot query field \"emoteCount\" on type \"Series\".",
            "    at Object.Field (/squid/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
            "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
            "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
            "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
            "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
            "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
            "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
          ]
        }
      }
    }
  ]
}
```

cc @roiLeo ^-^

**Comment by roiLeo** [comment]
wait what I can't find any references of emote in codebase
